### PR TITLE
Problem: required_signatures is static

### LINKED ISSUE #74: Number of required_signatures could be different with actual number of signatures required for transactions validation
The validators information is completely configured through bridge contracts and does not depend on `authorities.required_signatures` parameter of the bridge configuration.
The number of validators also could be changed during run-time and therefore `authorities.required_signatures` parameter will not reflect actual number of signatures required for a transaction validation.

The number of required signatures is required during `withdraw_relay` process to fetch signatures from foreign contract:
https://github.com/poanetwork/poa-bridge/blob/009d40aa504e7a48ddae6e965863b0338a8ebb0e/bridge/src/bridge/withdraw_relay.rs#L130-L134
Since the value of this parameter is picked up from configuration file it could be different from the actual number of signatures and it could cause:
1. the bridge cannot fetch enough number of signatures if the the value stored in the contract is greater than the value from the bridge config, so it will not be able to relay withdraws.
2. the bridge will fail on fetching signatures in the line
https://github.com/poanetwork/poa-bridge/blob/009d40aa504e7a48ddae6e965863b0338a8ebb0e/bridge/src/bridge/withdraw_relay.rs#L51
if the value stored in the contract is less than the value from the bridge configuration file.

The suggested changes are:
1. To get the address of Bridge Validators contracts from both home and foreign side.
2. To invoke `requiredSignatures()` on the foreign side for the same block which contains `CollectedSignatures` (an option could be to listen the event which will be introduced under https://github.com/poanetwork/poa-bridge-contracts/issues/27 as so update the value in the bridge instance on demand instead of polling)
3. To relay withdraw with the number of required signatures got in the step 2.

The situation when numbers of required signatures are different on both sides of bridges will be handled by monitoring. In order to make sure that number of the same the procedure to add/remove validators should make sure that no withdraw transactions are being sent at the moment of changing number of required signatures.

### PR DESCRIPTION
**Pull request by yrashk**
Validators' information is completely configured through validators
contracts and does not depend on `authorities.required_signatures`
parameter of bridge's configuration.

The number of validators also could be changed during run-time and
therefore `authorities.required_signatures` parameter will not reflect
the actual number of signatures required for transaction validation.

Solution: retrieve required_signatures from RequiredSignaturesChanged
event and requiredSignatures() method

Closes #74

### CODE REVIEW

**Comment by akolotov** [comment]
@yrashk could you please clarify a bit the method you are using? I went through the delta and, think, got quite confused.

**Comment by akolotov** [comment]
@yrashk @rstormsf do you think the set of changes could be reduced and logic will be more straightforward if we change `CollectedSignatures` event to:

`CollectedSignatures(address authorityResponsibleForRelay, bytes32 messageHash, uint256 NumberOfCollectedSignatures);`

So, in this case we don't need to watch for `RequiredSignaturesChanged()` event and don't need to call `requiredSignatures()` through RPC at all.

**Comment by yrashk** [comment]
@akolotov do you mean `CollectedSignatures(address authorityResponsibleForRelay, bytes32 messageHash, uint256 NumberOfRequiredSignatures)` ?

**Comment by yrashk** [comment]
I think this will greatly simplify bridge's code. Any thoughts on potential ways this can go wrong, though? Just to be on the safe side.

**Comment by rstormsf** [comment]
I don't see any problems

**Comment by akolotov** [comment]
@yrashk yes. This event was extended today under https://github.com/poanetwork/poa-bridge-contracts/pull/41.

https://github.com/poanetwork/poa-bridge-contracts/blob/aa811e7223847320dd83ce0a8a46d3bcad68dc8b/contracts/upgradeable_contracts/U_ForeignBridge.sol#L19

and 

https://github.com/poanetwork/poa-bridge-contracts/blob/aa811e7223847320dd83ce0a8a46d3bcad68dc8b/contracts/upgradeable_contracts/U_ForeignBridge.sol#L184-L187

**Comment by yrashk** [comment]
I updated this PR to use this new functionality. It has simplified this part of the bridge significantly!

**Comment by yrashk** [comment]
master with #93 has been tagged as v0.2.1

**Comment by akolotov** [comment]
@yrashk could you confirm that these changes has no conflicts and can be committed to master?

**Comment by yrashk** [comment]
@akolotov Yes, it has no conflicts and passes tests when attempted to merge into master (I just verified)

**Comment by akolotov** [comment]
Thank you! I will merge this PR in this case.

**Pull request merged**
